#Uesr server port
server:
  port: 9001

spring:
  application:
    name: api-gateway

#Zuul Routes
zuul:
  prefix: /api/v1
  routes:
    product-service:
      path: /product-service/**
      serviceId: product-service
      url: http://10.15.90.101:9002
    order-service:
      path: /order-service/**
      serviceId: order-service
    search-service:
      path: /search-service/**
      serviceId: search-service
    cart-service:
      path: /cart-service/**
      serviceId: cart-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.15.90.101:9000/eureka/

# Disable Spring Boot's "Whitelabel" default error page,
error:
  whitelabel:
    enabled: false