### Spring properties
# Service registers under this name
spring:
  application:
    name: product-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.15.90.101:9000/eureka/

# HTTP Server (Tomcat) Port
server:
  port: 9002

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false